package med.voll.api.medico;

public enum Especialidade {
    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA,
    PEDIATRIA,
    CLINICA_GERAL,
    NEUROLOGIA,
    PSIQUIATRIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    UROLOGIA,
    GASTROENTEROLOGIA
}
